FROM node:18

WORKDIR /app

# package.json 복사 및 의존성 설치
COPY package*.json ./
RUN npm install

# 소스 코드 복사
COPY . .

ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true
ENV FAST_REFRESH=true

# 개발 서버 실행 (핫 리로드 활성화)
CMD ["npm", "start"]
